Repository knaw-huc/broccoli, pull requests merged in 2025-05, with the labels that each got.

#88 Revert 7734ea2
  pom.xml
  src/main/kotlin/nl/knaw/huc/broccoli/resources/projects/ProjectsResource.kt
Labels: enhancement

#91 Originally: experiment with higher cache threshold
  pom.xml
  src/main/kotlin/nl/knaw/huc/broccoli/BroccoliApplication.kt
  src/main/kotlin/nl/knaw/huc/broccoli/config/BroccoliConfiguration.kt
  src/main/kotlin/nl/knaw/huc/broccoli/service/anno/AnnoRepo.kt
Labels: enhancement, experiment

#90 [Snyk] Upgrade io.github.knaw-huc:annorepo-client from 0.6.3 to 0.7.0
  pom.xml
Labels: dependencies

#92 [Snyk] Upgrade com.fasterxml.jackson.module:jackson-module-kotlin from 2.18.3 to 2.19.0
  pom.xml
Labels: dependencies

#93 [Snyk] Upgrade com.google.protobuf:protobuf-java from 3.25.6 to 3.25.7
  pom.xml
Labels: dependencies

#76 Integration test
  .gitignore
  pom.xml
  src/main/kotlin/nl/knaw/huc/broccoli/BroccoliApplication.kt
  src/main/kotlin/nl/knaw/huc/broccoli/api/IndexQuery.kt
  src/main/kotlin/nl/knaw/huc/broccoli/resources/AboutResource.kt
  src/main/kotlin/nl/knaw/huc/broccoli/resources/projects/ProjectsResource.kt
  src/test/kotlin/TestUtils.java
  src/test/kotlin/nl/knaw/huc/broccoli/resources/AboutResourceTest.kt
  src/test/kotlin/nl/knaw/huc/broccoli/resources/projects/ProjectsResourceTest.kt
  src/test/kotlin/nl/knaw/huc/broccoli/service/anno/AnnoRepoTest.kt
  src/test/resources/arAboutResponse.json
  src/test/resources/broccoliConfig.json
  src/test/resources/config.yml
  src/test/resources/projects/brintaConfig.json
  src/test/resources/projects/search/esRequest.json
  src/test/resources/projects/search/esResponse.json
  src/test/resources/projects/search/request.json
  src/test/resources/projects/search/response.json
Labels: enhancement, experiment

#80 Add annotations to trace api endpoint calls and method calls
  config.yml
  k8s/local/docker-compose-es.yml
  localhost.http
  pom.xml
  src/main/kotlin/nl/knaw/huc/broccoli/BroccoliApplication.kt
  src/main/kotlin/nl/knaw/huc/broccoli/log/RequestTraceLog.kt
  src/main/kotlin/nl/knaw/huc/broccoli/log/RequestTraceLogFilter.kt
  src/main/kotlin/nl/knaw/huc/broccoli/log/TraceLog.kt
  src/main/kotlin/nl/knaw/huc/broccoli/log/TraceLogAspect.kt
  src/main/kotlin/nl/knaw/huc/broccoli/resources/projects/ProjectsResource.kt
Labels: enhancement, experiment
